export default {
    ADD_ACTIVITY: 'ADD_RESUMED_ACTIVITY',
    ALTER_TASK: 'ALTER_TASK',
    DECREMENT_TIME: 'DECREMENT_TIME',
    RESET_TIME: 'RESET_TIME',
    START_TIME: 'START_TIME',
    STOP_TIME: 'STOP_TIME',
}
