export default {
    ADD_ACTIVITY: 'ADD_ACTIVITY',
    SET_INITIATED: 'SET_INITIATED',
    SET_PERCENTAGE_OF_PROGRESS: 'SET_PERCENTAGE_OF_PROGRESS',
    SET_RUNNING: 'SET_RUNNING',
    SET_SETTINGS: 'SET_SETTINGS',
    SET_TASK: 'SET_TASK',
    SET_TIME: 'SET_TIME'
}
